// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "EksilikApp",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .executable(name: "EksilikCoreHarness", targets: ["EksilikCoreHarness"]),
    ],
    dependencies: [
        .package(url: "https://github.com/tid-kijyun/Kanna.git", exact: "6.1.0"),
    ],
    targets: [
        .executableTarget(
            name: "EksilikCoreHarness",
            dependencies: ["Kanna"],
            path: ".",
            exclude: [
                "App",
                "Core/Auth",
                "Core/Compose",
                "Core/Images/ImagePipeline.swift",
                "Core/Navigation",
                "Core/Network/EksiRouter.swift",
                "Core/Network/HTTPClient.swift",
                "Core/Network/NetworkError.swift",
                "Core/Network/WebViewFetcher.swift",
                "Core/Parsing/ChannelParser.swift",
                "Core/Parsing/DebeParser.swift",
                "Core/Parsing/HTMLContentRenderer.swift",
                "Core/Parsing/MessageContentParser.swift",
                "Core/Parsing/MessageParser.swift",
                "Core/Parsing/SearchResultParser.swift",
                "Core/Storage/BlockedTopicStore.swift",
                "Core/Storage/CookiePersistence.swift",
                "Core/Storage/UserPreferences.swift",
                "Core/Theme",
                "Core/Widget",
                "EksilikApp-Info.plist",
                "EksilikApp.entitlements",
                "EksilikTests",
                "EksilikWidget",
                "EksilikWidget-Info.plist",
                "EksilikWidget.entitlements",
                "ExportOptions.plist",
                "Models/Channel.swift",
                "Models/DebeEntry.swift",
                "Models/Message.swift",
                "Models/MessageThread.swift",
                "Models/SearchResult.swift",
                "Resources",
                "Services",
                "ViewModels",
                "Views",
                "CODE_OF_CONDUCT.md",
                "CONTRIBUTING.md",
                "LICENSE",
                "PRIVACY.md",
                "README.md",
                "SECURITY.md",
                "SUPPORT.md",
                "docs",
                "metadata",
                "project.yml",
            ],
            sources: [
                "Core/Parsing/AuthParser.swift",
                "Core/Parsing/EntryPageParser.swift",
                "Core/Parsing/HTMLParser.swift",
                "Core/Parsing/PaginationParser.swift",
                "Core/Parsing/ProfileConnectionParser.swift",
                "Core/Parsing/TopicListParser.swift",
                "Core/Parsing/UserProfileParser.swift",
                "Core/Network/EksiEndpoint.swift",
                "Core/Network/TopicRequest.swift",
                "Core/Loading/SkeletonLayout.swift",
                "Core/Links/ExternalLinkPolicy.swift",
                "Core/Presentation/EntryLayoutStyle.swift",
                "Core/Presentation/EntryListChromePolicy.swift",
                "Core/Presentation/FollowingFeedSection.swift",
                "Core/Presentation/HomeNavigationStyle.swift",
                "Core/Presentation/MainTab.swift",
                "Core/Presentation/SettingsPresentationPolicy.swift",
                "Core/Search/SearchPresentation.swift",
                "Core/Images/ImageURLNormalizer.swift",
                "Core/Storage/OfflineTopicStore.swift",
                "Core/Strings.swift",
                "Models/Author.swift",
                "Models/Entry.swift",
                "Models/EntryFilter.swift",
                "Models/OfflineTopic.swift",
                "Models/Pagination.swift",
                "Models/ProfileConnection.swift",
                "Models/Topic.swift",
                "Models/UserProfile.swift",
                "CoreTestHarness/main.swift",
            ]
        ),
    ]
)
